// Collection of cool GIFs for different sections
export const sectionGifs = {
  hero: [
    {
      id: 'coding-1',
      src: 'https://media.giphy.com/media/L1R1tvI9svkIWwpVYr/giphy.gif',
      alt: 'Coding animation',
      position: 'right' as const,
      width: 120,
      height: 120,
      opacity: 0.78,
      animation: 'float' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'shadow' as const,
    },
    {
      id: 'tech-1',
      src: 'https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif',
      alt: 'Technology animation',
      position: 'left' as const,
      width: 110,
      height: 110,
      opacity: 0.65,
      animation: 'pulse' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'gradient' as const,
    },
  ],
  about: [
    {
      id: 'brain-1',
      src: 'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
      alt: 'Brain thinking animation',
      position: 'left' as const,
      width: 100,
      height: 100,
      opacity: 0.2,
      animation: 'bounce' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'line' as const,
    },
    {
      id: 'learning-1',
      src: 'https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif',
      alt: 'Learning animation',
      position: 'right' as const,
      width: 95,
      height: 95,
      opacity: 0.18,
      animation: 'float' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'shadow' as const,
    },
  ],
  projects: [
    {
      id: 'rocket-1',
      src: 'https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif',
      alt: 'Rocket launch animation',
      position: 'right' as const,
      width: 110,
      height: 110,
      opacity: 0.22,
      animation: 'float' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'gradient' as const,
    },
    {
      id: 'code-1',
      src: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
      alt: 'Code typing animation',
      position: 'left' as const,
      width: 105,
      height: 105,
      opacity: 0.2,
      animation: 'pulse' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'line' as const,
    },
  ],
  contact: [
    {
      id: 'message-1',
      src: 'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
      alt: 'Message animation',
      position: 'left' as const,
      width: 100,
      height: 100,
      opacity: 0.2,
      animation: 'bounce' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'shadow' as const,
    },
    {
      id: 'connect-1',
      src: 'https://media.giphy.com/media/3o7btM0ScE3jZ8g1sI/giphy.gif',
      alt: 'Connection animation',
      position: 'right' as const,
      width: 95,
      height: 95,
      opacity: 0.18,
      animation: 'float' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'gradient' as const,
    },
  ],
  resume: [
    {
      id: 'document-1',
      src: 'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
      alt: 'Document animation',
      position: 'right' as const,
      width: 100,
      height: 100,
      opacity: 0.2,
      animation: 'pulse' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'line' as const,
    },
    {
      id: 'success-1',
      src: 'https://media.giphy.com/media/3o7btM0ScE3jZ8g1sI/giphy.gif',
      alt: 'Success animation',
      position: 'left' as const,
      width: 95,
      height: 95,
      opacity: 0.18,
      animation: 'bounce' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'shadow' as const,
    },
  ],
  services: [
    {
      id: 'service-1',
      src: 'https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif',
      alt: 'Service animation',
      position: 'left' as const,
      width: 100,
      height: 100,
      opacity: 0.2,
      animation: 'float' as const,
      speed: 'slow' as const,
      showSeparator: true,
      separatorType: 'gradient' as const,
    },
    {
      id: 'support-1',
      src: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
      alt: 'Support animation',
      position: 'right' as const,
      width: 95,
      height: 95,
      opacity: 0.18,
      animation: 'pulse' as const,
      speed: 'normal' as const,
      showSeparator: true,
      separatorType: 'line' as const,
    },
  ],
};

// Alternative GIFs for variety
export const alternativeGifs = {
  hero: [
    'https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif',
    'https://media.giphy.com/media/L1R1tvI9svkIWwpVYr/giphy.gif',
    'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  ],
  about: [
    'https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif',
    'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
    'https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif',
  ],
  projects: [
    'https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif',
    'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
    'https://media.giphy.com/media/L1R1tvI9svkIWwpVYr/giphy.gif',
  ],
  contact: [
    'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
    'https://media.giphy.com/media/3o7btM0ScE3jZ8g1sI/giphy.gif',
    'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  ],
  resume: [
    'https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif',
    'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
    'https://media.giphy.com/media/3o7btM0ScE3jZ8g1sI/giphy.gif',
  ],
  services: [
    'https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif',
    'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
    'https://media.giphy.com/media/3o7btM0ScE3jZ8g1sI/giphy.gif',
  ],
};
