export const pageCards = [
  {
    title: 'ATS Checker',
    description:
      "Check your resume's ATS compatibility and get detailed analysis reports.",
    href: '/resume/ats-checker',
    gifSrc: 'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
    gifAlt: 'Analysis animation',
    iconName: 'Check',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-teal-600',
    delay: 0,
  },
  {
    title: 'Resume Builder',
    description:
      'Create professional resumes with our advanced builder tool and templates.',
    href: '/resume/builder',
    gifSrc: 'https://media.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.gif',
    gifAlt: 'Document building animation',
    iconName: 'File',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-600',
    delay: 200,
  },
  {
    title: 'Resume Templates',
    description:
      'Browse beautiful, professional resume templates and export in multiple formats.',
    href: '/resume/templates',
    gifSrc: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
    gifAlt: 'Template gallery animation',
    iconName: 'Layout',
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-600',
    delay: 400,
  },
  {
    title: 'About Me',
    description:
      'Learn about my journey, skills, and passion for creating amazing digital experiences.',
    href: '/about',
    gifSrc: 'https://media.giphy.com/media/26tn33aiTi1jkl6H6/giphy.gif',
    gifAlt: 'Brain thinking animation',
    iconName: 'Briefcase',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-purple-600',
    delay: 600,
  },
  {
    title: 'My Projects',
    description:
      'Explore my portfolio of web applications, mobile apps, and creative solutions.',
    href: '/projects',
    gifSrc: 'https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif',
    gifAlt: 'Rocket launch animation',
    iconName: 'Globe',
    gradientFrom: 'from-green-500',
    gradientTo: 'to-blue-600',
    delay: 800,
  },
  {
    title: 'Blog & Insights',
    description:
      'Read my latest thoughts on web development, technology trends, and best practices.',
    href: '/blog',
    gifSrc: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif',
    gifAlt: 'Learning animation',
    iconName: 'Star',
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-600',
    delay: 600,
  },
  {
    title: 'Get In Touch',
    description:
      "Ready to work together? Let's discuss your next project and bring ideas to life.",
    href: '/contact',
    gifSrc: 'https://media.giphy.com/media/3o7aD2d7hy9ktXNDP2/giphy.gif',
    gifAlt: 'Message animation',
    iconName: 'Email',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-teal-600',
    delay: 700,
  },
  {
    title: 'Services',
    description:
      'Discover the range of development services I offer to help grow your business.',
    href: '/services',
    gifSrc: 'https://media.giphy.com/media/L1R1tvI9svkIWwpVYr/giphy.gif',
    gifAlt: 'Service animation',
    iconName: 'Settings',
    gradientFrom: 'from-indigo-500',
    gradientTo: 'to-purple-600',
    delay: 800,
  },
] as const;
