[build]
# Increase build timeout for ML dependencies
nixpacksVersion = "1.32.1"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
