export interface JobProfile {
  id: string;
  name: string;
  category: string;
  keywords: string[];
  skills: string[];
  experience: string[];
  certifications: string[];
  education: string[];
  actionVerbs: string[];
  buzzwords: string[];
}

export const jobProfiles: JobProfile[] = [
  // Technology - Software Engineering
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    category: 'Technology',
    keywords: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C++',
      'C#',
      'Go',
      'Rust',
      'React',
      'Vue',
      'Angular',
      'Node.js',
      'Express',
      'Django',
      'Flask',
      'Spring Boot',
      'ASP.NET',
      'Laravel',
      'Ruby on Rails',
      'SQL',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Elasticsearch',
      'AWS',
      'Azure',
      'GCP',
      'Docker',
      'Kubernetes',
      'Jenkins',
      'Git',
      'REST API',
      'GraphQL',
      'Microservices',
      'Agile',
      'Scrum',
      'DevOps',
    ],
    skills: [
      'Programming',
      'Problem Solving',
      'Algorithm Design',
      'Data Structures',
      'Software Architecture',
      'Code Review',
      'Testing',
      'Debugging',
      'Version Control',
      'CI/CD',
      'Cloud Computing',
      'Database Design',
    ],
    experience: [
      '2+ years',
      '3+ years',
      '5+ years',
      'Senior level',
      'Lead developer',
      'Full-stack development',
      'Backend development',
      'Frontend development',
    ],
    certifications: [
      'AWS Certified Developer',
      'Google Cloud Professional',
      'Microsoft Azure Developer',
      'Oracle Java Certification',
    ],
    education: [
      'Computer Science',
      'Software Engineering',
      'Information Technology',
      'Bachelor of Science',
      'Master of Science',
    ],
    actionVerbs: [
      'Developed',
      'Implemented',
      'Designed',
      'Architected',
      'Optimized',
      'Deployed',
      'Maintained',
      'Debugged',
      'Tested',
      'Refactored',
    ],
    buzzwords: [
      'Machine Learning',
      'AI',
      'Blockchain',
      'IoT',
      'Serverless',
      'Edge Computing',
      'Quantum Computing',
      'AR/VR',
      '5G',
    ],
  },

  // Technology - Data Science
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    category: 'Technology',
    keywords: [
      'Python',
      'R',
      'SQL',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Jupyter',
      'Matplotlib',
      'Seaborn',
      'Plotly',
      'Apache Spark',
      'Hadoop',
      'Kafka',
      'Airflow',
      'MLflow',
      'Machine Learning',
      'Deep Learning',
      'NLP',
      'Computer Vision',
      'Statistics',
      'Probability',
      'Linear Algebra',
      'Calculus',
      'A/B Testing',
      'Feature Engineering',
      'Model Deployment',
    ],
    skills: [
      'Statistical Analysis',
      'Machine Learning',
      'Data Visualization',
      'Data Mining',
      'Predictive Modeling',
      'Experimental Design',
      'Business Intelligence',
      'Data Storytelling',
      'Critical Thinking',
    ],
    experience: [
      '2+ years',
      '3+ years',
      '5+ years',
      'PhD',
      'Research experience',
      'Industry experience',
      'Academic background',
    ],
    certifications: [
      'Google Data Analytics',
      'AWS Machine Learning',
      'Microsoft Azure Data Scientist',
      'IBM Data Science',
    ],
    education: [
      'Data Science',
      'Statistics',
      'Mathematics',
      'Computer Science',
      'Physics',
      'Economics',
      'PhD',
      'Master of Science',
    ],
    actionVerbs: [
      'Analyzed',
      'Modeled',
      'Predicted',
      'Visualized',
      'Optimized',
      'Researched',
      'Discovered',
      'Validated',
      'Implemented',
      'Deployed',
    ],
    buzzwords: [
      'Big Data',
      'AI Ethics',
      'Explainable AI',
      'AutoML',
      'MLOps',
      'Data Mesh',
      'Real-time Analytics',
      'Edge AI',
    ],
  },

  // Business - Marketing
  {
    id: 'marketing-manager',
    name: 'Marketing Manager',
    category: 'Business',
    keywords: [
      'Digital Marketing',
      'SEO',
      'SEM',
      'PPC',
      'Google Ads',
      'Facebook Ads',
      'Content Marketing',
      'Social Media Marketing',
      'Email Marketing',
      'Marketing Automation',
      'HubSpot',
      'Salesforce',
      'Google Analytics',
      'Adobe Creative Suite',
      'Canva',
      'Figma',
      'WordPress',
      'Campaign Management',
      'Brand Management',
      'Market Research',
      'Customer Acquisition',
      'Lead Generation',
      'Conversion Optimization',
    ],
    skills: [
      'Strategic Planning',
      'Campaign Management',
      'Brand Development',
      'Market Research',
      'Data Analysis',
      'Creative Direction',
      'Project Management',
      'Team Leadership',
      'Communication',
    ],
    experience: [
      '3+ years',
      '5+ years',
      'Management experience',
      'Team leadership',
      'Campaign management',
      'Brand management',
    ],
    certifications: [
      'Google Analytics',
      'Google Ads',
      'Facebook Blueprint',
      'HubSpot Marketing',
      'Hootsuite Social Media',
    ],
    education: [
      'Marketing',
      'Business Administration',
      'Communications',
      'Bachelor of Business',
      'MBA',
      'Master of Marketing',
    ],
    actionVerbs: [
      'Developed',
      'Executed',
      'Managed',
      'Optimized',
      'Analyzed',
      'Launched',
      'Increased',
      'Improved',
      'Generated',
      'Led',
    ],
    buzzwords: [
      'Personalization',
      'Omnichannel',
      'Customer Journey',
      'Marketing Technology',
      'Attribution Modeling',
      'Privacy-First',
    ],
  },

  // Business - Sales
  {
    id: 'sales-representative',
    name: 'Sales Representative',
    category: 'Business',
    keywords: [
      'CRM',
      'Salesforce',
      'HubSpot',
      'Pipedrive',
      'Zoho CRM',
      'Lead Generation',
      'Prospecting',
      'Cold Calling',
      'Email Outreach',
      'Sales Pipeline',
      'Deal Management',
      'Customer Relationship',
      'Negotiation',
      'Closing',
      'Account Management',
      'Territory Management',
      'Sales Forecasting',
      'Revenue Generation',
      'Customer Acquisition',
    ],
    skills: [
      'Communication',
      'Negotiation',
      'Relationship Building',
      'Persuasion',
      'Active Listening',
      'Problem Solving',
      'Time Management',
      'Goal Setting',
      'Presentation Skills',
    ],
    experience: [
      '1+ years',
      '2+ years',
      '3+ years',
      'Sales experience',
      'B2B sales',
      'B2C sales',
      'Inside sales',
      'Outside sales',
    ],
    certifications: [
      'Salesforce Certified',
      'HubSpot Sales',
      'Challenger Sale',
      'SPIN Selling',
      'Sandler Training',
    ],
    education: [
      'Business',
      'Sales',
      'Marketing',
      'Communications',
      'Bachelor of Business',
      'Associate Degree',
    ],
    actionVerbs: [
      'Generated',
      'Closed',
      'Negotiated',
      'Presented',
      'Followed up',
      'Qualified',
      'Converted',
      'Exceeded',
      'Achieved',
      'Delivered',
    ],
    buzzwords: [
      'Sales Enablement',
      'Revenue Operations',
      'Customer Success',
      'Account-Based Marketing',
      'Sales Intelligence',
    ],
  },

  // Healthcare - Nursing
  {
    id: 'registered-nurse',
    name: 'Registered Nurse',
    category: 'Healthcare',
    keywords: [
      'Patient Care',
      'Medical Assessment',
      'Medication Administration',
      'Vital Signs',
      'Electronic Health Records',
      'Epic',
      'Cerner',
      'Nursing Care Plans',
      'Patient Education',
      'Health Promotion',
      'Disease Prevention',
      'Infection Control',
      'Emergency Care',
      'Critical Care',
      'Medical-Surgical',
      'Pediatrics',
      'Geriatrics',
    ],
    skills: [
      'Patient Assessment',
      'Clinical Skills',
      'Communication',
      'Critical Thinking',
      'Empathy',
      'Attention to Detail',
      'Time Management',
      'Teamwork',
      'Problem Solving',
    ],
    experience: [
      '1+ years',
      '2+ years',
      '3+ years',
      'Clinical experience',
      'Hospital experience',
      'Long-term care',
      'Home health',
    ],
    certifications: [
      'RN License',
      'BLS',
      'ACLS',
      'PALS',
      'CPR',
      'Specialty Certifications',
      'Continuing Education',
    ],
    education: [
      'Nursing',
      'Bachelor of Science in Nursing',
      'Associate Degree in Nursing',
      'Diploma in Nursing',
      'Master of Science in Nursing',
    ],
    actionVerbs: [
      'Assessed',
      'Monitored',
      'Administered',
      'Educated',
      'Coordinated',
      'Documented',
      'Collaborated',
      'Advocated',
      'Implemented',
      'Evaluated',
    ],
    buzzwords: [
      'Telehealth',
      'Digital Health',
      'Precision Medicine',
      'Population Health',
      'Value-Based Care',
    ],
  },
];

export const getJobProfileById = (id: string): JobProfile | undefined => {
  return jobProfiles.find(profile => profile.id === id);
};

export const getJobProfilesByCategory = (category: string): JobProfile[] => {
  return jobProfiles.filter(profile => profile.category === category);
};

export const getAllCategories = (): string[] => {
  return [...new Set(jobProfiles.map(profile => profile.category))];
};
